from laser_measles.components import BaseCaseSurveillanceTracker, BaseCaseSurveillanceParams

class CaseSurveillanceParams(BaseCaseSurveillanceParams): ...

class CaseSurveillanceTracker(BaseCaseSurveillanceTracker): ...
