from laser_measles.components import BasePopulationTracker, BasePopulationTrackerParams

class PopulationTracker(BasePopulationTracker): ...

class PopulationTrackerParams(BasePopulationTrackerParams): ...